apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: kargo-simple
  annotations:
    kargo.akuity.io/color: red
spec:
  subscriptions:
    warehouse: guestbook
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/PhilippParis/kargo-simple.git
      writeBranch: main
      helm:
        images:
        - image: ghcr.io/philippparis/guestbook
          key: tag
          value: Tag
          valuesFilePath: env/dev/values-dev.yaml

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: test
  namespace: kargo-simple
  annotations:
    kargo.akuity.io/color: amber
spec:
  subscriptions:
    upstreamStages:
      - name: dev
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/PhilippParis/kargo-simple.git
      writeBranch: main
      helm:
        images:
        - image: ghcr.io/philippparis/guestbook
          key: tag
          value: Tag
          valuesFilePath: env/test/values-test.yaml

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: kargo-simple
  annotations:
    kargo.akuity.io/color: violet
spec:
  subscriptions:
    upstreamStages:
      - name: test
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/PhilippParis/kargo-simple.git
      writeBranch: main
      helm:
        images:
        - image: ghcr.io/philippparis/guestbook
          key: tag
          value: Tag
          valuesFilePath: env/prod/values-prod.yaml
