apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: kargo-simple
  annotations:
    kargo.akuity.io/color: red
spec:
  subscriptions:
    warehouse: guestbook
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/PhilippParis/kargo-simple.git
      writeBranch: env/dev
      pullRequest: {} # not supported for 'render'!
      render: {}
      #helm:
      #  images:
      #  - image: ghcr.io/philippparis/guestbook
      #    key: image.tag
      #    value: Tag
      #    valuesFilePath: values-dev.yaml

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: test
  namespace: kargo-simple
  annotations:
    kargo.akuity.io/color: amber
spec:
  subscriptions:
    upstreamStages:
      - name: dev
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/PhilippParis/kargo-simple.git
      writeBranch: env/test
      pullRequest: {} # not supported for 'render'!
      render: {}
      #helm:
      #  images:
      #  - image: ghcr.io/philippparis/guestbook
      #    key: image.tag
      #    value: Tag
      #    valuesFilePath: values-test.yaml

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: kargo-simple
  annotations:
    kargo.akuity.io/color: violet
spec:
  subscriptions:
    upstreamStages:
      - name: test
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/PhilippParis/kargo-simple.git
      writeBranch: env/prod
      pullRequest: {} # not supported for 'render'!
      render: {}
      #helm:
      #  images:
      #  - image: ghcr.io/philippparis/guestbook
      #    key: image.tag
      #    value: Tag
      #    valuesFilePath: values-prod.yaml
